let Giraffe: Sprite = null
let race_started = false
let textSprite: TextSprite = null
let Traffic_Light = sprites.create(img`
    ...............ffffffffffffffffffffffffffff.................
    ...............ffffffffffffffffffffffffffff.................
    ...............ffffffffffffffffffffffffffff.................
    ...............ffffffffffffffffffffffffffff.................
    ...............ffffffffffffffffffffffffffff.................
    ...............ffffffffffbbbbbbbbbfffffffff.................
    ...............ffffffffbbbbbbbbbbbbbfffffff.................
    ...............fffffffbbbbbbbbbbbbbbbffffff.................
    ...............ffffffbbbbbbbbbbbbbbbbbfffff.................
    ...............fffffbbbbbbbbbbbbbbbbbbbffff.................
    ...............fffffbbbbbbbbbbbbbbbbbbbffff.................
    ...............ffffbbbbbbbbbbbbbbbbbbbbbfff.................
    ...............ffffbbbbbbbbbbbbbbbbbbbbbfff.................
    ...............ffffbbbbbbbbbbbbbbbbbbbbbfff.................
    ...............ffffbbbbbbbbbbbbbbbbbbbbbfff.................
    ...............ffffbbbbbbbbbbbbbbbbbbbbbfff.................
    ...............ffffbbbbbbbbbbbbbbbbbbbbbfff.................
    ...............ffffbbbbbbbbbbbbbbbbbbbbbfff.................
    ...............ffffbbbbbbbbbbbbbbbbbbbbbfff.................
    ...............ffffbbbbbbbbbbbbbbbbbbbbbfff.................
    ...............fffffbbbbbbbbbbbbbbbbbbbffff.................
    ...............fffffbbbbbbbbbbbbbbbbbbbffff.................
    ...............ffffffbbbbbbbbbbbbbbbbbfffff.................
    ...............fffffffbbbbbbbbbbbbbbbffffff.................
    ...............ffffffffbbbbbbbbbbbbbfffffff.................
    ...............ffffffffffbbbbbbbbbfffffffff.................
    ...............ffffffffffffffffffffffffffff.................
    ...............ffffffffffffffffffffffffffff.................
    ...............ffffffffffffffffffffffffffff.................
    ...............ffffffffffffffffffffffffffff.................
    ...............ffffffffffeeeeeeeeefffffffff.................
    ...............ffffffffeeeeeeeeeeeeefffffff.................
    ...............fffffffeeeeeeeeeeeeeeeffffff.................
    ...............ffffffeeeeeeeeeeeeeeeeefffff.................
    ...............fffffeeeeeeeeeeeeeeeeeeeffff.................
    ...............fffffeeeeeeeeeeeeeeeeeeeffff.................
    ...............ffffeeeeeeeeeeeeeeeeeeeeefff.................
    ...............ffffeeeeeeeeeeeeeeeeeeeeefff.................
    ...............ffffeeeeeeeeeeeeeeeeeeeeefff.................
    ...............ffffeeeeeeeeeeeeeeeeeeeeefff.................
    ...............ffffeeeeeeeeeeeeeeeeeeeeefff.................
    ...............ffffeeeeeeeeeeeeeeeeeeeeefff.................
    ...............ffffeeeeeeeeeeeeeeeeeeeeefff.................
    ...............ffffeeeeeeeeeeeeeeeeeeeeefff.................
    ...............ffffeeeeeeeeeeeeeeeeeeeeefff.................
    ...............fffffeeeeeeeeeeeeeeeeeeeffff.................
    ...............fffffeeeeeeeeeeeeeeeeeeeffff.................
    ...............ffffffeeeeeeeeeeeeeeeeefffff.................
    ...............fffffffeeeeeeeeeeeeeeeffffff.................
    ...............ffffffffeeeeeeeeeeeeefffffff.................
    ...............ffffffffffeeeeeeeeefffffffff.................
    ...............ffffffffffffffffffffffffffff.................
    ...............ffffffffffffffffffffffffffff.................
    ...............ffffffffffffffffffffffffffff.................
    ...............ffffffffffffffffffffffffffff.................
    ...............ffffffffffffffffffffffffffff.................
    ...............ffffffffffffffffffffffffffff.................
    ...............ffffffffff666666666fffffffff.................
    ...............ffffffff6666666666666fffffff.................
    ...............fffffff666666666666666ffffff.................
    ...............ffffff66666666666666666fffff.................
    ...............fffff6666666666666666666ffff.................
    ...............fffff6666666666666666666ffff.................
    ...............ffff666666666666666666666fff.................
    ...............ffff666666666666666666666fff.................
    ...............ffff666666666666666666666fff.................
    ...............ffff666666666666666666666fff.................
    ...............ffff666666666666666666666fff.................
    ...............ffff666666666666666666666fff.................
    ...............ffff666666666666666666666fff.................
    ...............ffff666666666666666666666fff.................
    ...............ffff666666666666666666666fff.................
    ...............fffff6666666666666666666ffff.................
    ...............fffff6666666666666666666ffff.................
    ...............ffffff66666666666666666fffff.................
    ...............fffffff666666666666666ffffff.................
    ...............ffffffff6666666666666fffffff.................
    ...............ffffffffff666666666fffffffff.................
    ...............ffffffffffffffffffffffffffff.................
    ...............ffffffffffffffffffffffffffff.................
    `, SpriteKind.Player)
scene.setBackgroundColor(9)
tiles.setTilemap(tilemap`level2`)
let racer_1 = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Player)
let racer_2 = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Player)
timer.background(function () {
    pause(1000)
    Traffic_Light.image.replace(11, 2)
    pause(1000)
    Traffic_Light.image.replace(2, 11)
    pause(100)
    Traffic_Light.image.replace(14, 5)
    pause(1000)
    Traffic_Light.image.replace(5, 14)
    pause(100)
    Traffic_Light.image.replace(6, 7)
    pause(1000)
    Traffic_Light.destroy()
    textSprite = textsprite.create("GO!")
    textSprite.setOutline(1, 6)
    textSprite.setMaxFontHeight(64)
    textSprite.setPosition(80, 60)
    pause(1000)
    textSprite.destroy()
    race_started = true
})
animation.runImageAnimation(
Giraffe,
[img`
    .........................
    ..............aaaaaa.....
    .............aaaaaaa.....
    .............aafffff.....
    .............afaadff.....
    .............aaaadddd....
    .............aaaadddd....
    ......aaaaaaaaaaaaaa.....
    .....aaaaaaaaaaaaa.......
    ...aaaaaaaaaaaaaaa.......
    ...aaaaaaaaaaaaaaa.......
    ...aaaaaaaaaaaaaaa.......
    .....aaaaaaaaaaaaa.......
    .....aaaaaaaaaaaa........
    .....aaaaaaaaaaaa........
    ......aaaaaaaaaa.........
    .......aa.cc..aa.........
    .......aa.cc..aa.........
    .......aa.cc..aa.........
    .........................
    `,img`
    .........................
    ..............aaaaaa.....
    .............aaaaaaa.....
    .............aafffff.....
    .............afaadff.....
    .............aaaadddd....
    .............aaaadddd....
    ......aaaaaaaaaaaaaa.....
    .....aaaaaaaaaaaaa.......
    ...aaaaaaaaaaaaaaa.......
    ...aaaaaaaaaaaaaaa.......
    ...aaaaaaaaaaaaaaa.......
    .....aaaaaaaaaaaaa.......
    .....aaaaaaaaaaaa........
    .....aaaaaaaaaaaac.......
    ......aaaaaaaaaacc.......
    ......aa.cc..aa.ccc......
    ......aa.cc..aa..cc......
    ......aa.cc..aa..cc......
    .........................
    `,img`
    .........................
    ..............aaaaaa.....
    .............aaaaaaa.....
    .............aafffff.....
    .............afaadff.....
    .............aaaadddd....
    .............aaaadddd....
    ......aaaaaaaaaaaaaa.....
    .....aaaaaaaaaaaaa.......
    ...aaaaaaaaaaaaaaa.......
    ...aaaaaaaaaaaaaaa.......
    ...aaaaaaaaaaaaaaa.......
    .....aaaaaaaaaaaaa.......
    .....aaaaaaaaaaaa........
    .....aaaaaaaaaaaa........
    ......aaaaaaaaaa.........
    .....aa.cc..ccaa.........
    .....aa.cc.cccaa.........
    .....aa.cc.cc.aa.........
    .........................
    `,img`
    .........................
    ..............aaaaaa.....
    .............aaaaaaa.....
    .............aafffff.....
    .............afaadff.....
    .............aaaadddd....
    .............aaaadddd....
    ......aaaaaaaaaaaaaa.....
    .....aaaaaaaaaaaaa.......
    ...aaaaaaaaaaaaaaa.......
    ...aaaaaaaaaaaaaaa.......
    ...aaaaaaaaaaaaaaa.......
    .....aaaaaaaaaaaaa.......
    .....aaaaaaaaaaaa........
    .....aaaaaaaaaaaa........
    ......aaaaaaaaaa.........
    .....aa.cc..ccaa.........
    .....aa.cc.cccaa.........
    .....aa.cc.cc.aa.........
    .........................
    `,img`
    .........................
    ..............aaaaaa.....
    .............aaaaaaa.....
    .............aafffff.....
    .............afaadff.....
    .............aaaadddd....
    .............aaaadddd....
    ......aaaaaaaaaaaaaa.....
    .....aaaaaaaaaaaaa.......
    ...aaaaaaaaaaaaaaa.......
    ...aaaaaaaaaaaaaaa.......
    ...aaaaaaaaaaaaaaa.......
    .....aaaaaaaaaaaaa.......
    .....aaaaaaaaaaaa........
    .....aaaaaaaaaaaa........
    ......aaaaaaaaaa.........
    .....ccaaa..ccaa.........
    ....ccc.aaacccaa.........
    ....cc...aacc.aa.........
    .........................
    `,img`
    .........................
    ..............aaaaaa.....
    .............aaaaaaa.....
    .............aafffff.....
    .............afaadff.....
    .............aaaadddd....
    .............aaaadddd....
    ......aaaaaaaaaaaaaa.....
    .....aaaaaaaaaaaaa.......
    ...aaaaaaaaaaaaaaa.......
    ...aaaaaaaaaaaaaaa.......
    ...aaaaaaaaaaaaaaa.......
    .....aaaaaaaaaaaaa.......
    .....aaaaaaaaaaaa........
    .....aaaaaaaaaaaa........
    ......aaaaaaaaaa.........
    .....aa.aa..ccaa.........
    .....aa.aa.cccaa.........
    .....aa.aa.cc.aa.........
    .........................
    `],
200,
false
)
animation.runImageAnimation(
Giraffe,
[img`
    ..........555.f.f555
    ...........53555535.
    ...........fffffff..
    ..........f.55fff55.
    ............5555555.
    ............555555f.
    ...........55e5..ff.
    ...........5555.....
    ...........5e55.....
    ...........5555.....
    ...........5555.....
    ...........55e5.....
    ..........55555.....
    .........555555.....
    .....5555e5555......
    ....555eee55555.....
    ...55555555555......
    ...5ee5555ee55......
    ...55ee555e554......
    ...55555555.44......
    ...55.44.55.44......
    ...55.44.55.44......
    ...55.44.55.44......
    ...55.44.55.44......
    ...55.44.55.........
    `,img`
    ..........555.f.f555
    ...........53555535.
    ...........fffffff..
    ..........f.55fff55.
    ............5555555.
    ............555555f.
    ...........55e5..ff.
    ...........5555.....
    ...........5e55.....
    ...........5555.....
    ...........5555.....
    ...........55e5.....
    ..........55555.....
    .........555555.....
    .....5555e5555......
    ....555eee55555.....
    ...55555555555......
    ...5ee5555ee55......
    ...55ee555e554......
    ..555555555544......
    .555..44..5554......
    .55...44...555......
    .55...44....555.....
    .55...44....4555....
    .55...44......55....
    `,img`
    ..........555.f.f555
    ...........53555535.
    ...........fffffff..
    ..........f.55fff55.
    ............5555555.
    ............555555f.
    ...........55e5..ff.
    ...........5555.....
    ...........5e55.....
    ...........5555.....
    ...........5555.....
    ...........55e5.....
    ..........55555.....
    .........555555.....
    .....5555e5555......
    ....555eee55555.....
    ...55555555555......
    ...5ee5555ee55......
    ...55ee555e554......
    ....5555555544......
    ....5544..555.......
    ...45544..4555......
    ..4455...44.555.....
    .44455...44..555....
    .44.55...44...55....
    `],
200,
false
)
