namespace SpriteKind {
    export const yes = SpriteKind.create()
    export const no = SpriteKind.create()
    export const flag = SpriteKind.create()
    export const p1 = SpriteKind.create()
    export const p2 = SpriteKind.create()
    export const ob = SpriteKind.create()
}
controller.anyButton.onEvent(ControllerButtonEvent.Pressed, function () {
    if (Traffic_Light) {
        animation.runImageAnimation(
        racer_1,
        [img`
            .........................
            ..............aaaaaa.....
            .............aaaaaaa.....
            .............aafffff.....
            .............afaadff.....
            .............aaaadddd....
            .............aaaadddd....
            ......aaaaaaaaaaaaaa.....
            .....aaaaaaaaaaaaa.......
            ...aaaaaaaaaaaaaaa.......
            ...aaaaaaaaaaaaaaa.......
            ...aaaaaaaaaaaaaaa.......
            .....aaaaaaaaaaaaa.......
            .....aaaaaaaaaaaa........
            .....aaaaaaaaaaaa........
            ......aaaaaaaaaa.........
            .......aa.cc..aa.........
            .......aa.cc..aa.........
            .......aa.cc..aa.........
            .........................
            `,img`
            .........................
            ..............aaaaaa.....
            .............aaaaaaa.....
            .............aafffff.....
            .............afaadff.....
            .............aaaadddd....
            .............aaaadddd....
            ......aaaaaaaaaaaaaa.....
            .....aaaaaaaaaaaaa.......
            ...aaaaaaaaaaaaaaa.......
            ...aaaaaaaaaaaaaaa.......
            ...aaaaaaaaaaaaaaa.......
            .....aaaaaaaaaaaaa.......
            .....aaaaaaaaaaaa........
            .....aaaaaaaaaaaac.......
            ......aaaaaaaaaacc.......
            ......aa.cc..aa.ccc......
            ......aa.cc..aa..cc......
            ......aa.cc..aa..cc......
            .........................
            `,img`
            .........................
            ..............aaaaaa.....
            .............aaaaaaa.....
            .............aafffff.....
            .............afaadff.....
            .............aaaadddd....
            .............aaaadddd....
            ......aaaaaaaaaaaaaa.....
            .....aaaaaaaaaaaaa.......
            ...aaaaaaaaaaaaaaa.......
            ...aaaaaaaaaaaaaaa.......
            ...aaaaaaaaaaaaaaa.......
            .....aaaaaaaaaaaaa.......
            .....aaaaaaaaaaaa........
            .....aaaaaaaaaaaa........
            ......aaaaaaaaaa.........
            .....aa.cc..ccaa.........
            .....aa.cc.cccaa.........
            .....aa.cc.cc.aa.........
            .........................
            `,img`
            .........................
            ..............aaaaaa.....
            .............aaaaaaa.....
            .............aafffff.....
            .............afaadff.....
            .............aaaadddd....
            .............aaaadddd....
            ......aaaaaaaaaaaaaa.....
            .....aaaaaaaaaaaaa.......
            ...aaaaaaaaaaaaaaa.......
            ...aaaaaaaaaaaaaaa.......
            ...aaaaaaaaaaaaaaa.......
            .....aaaaaaaaaaaaa.......
            .....aaaaaaaaaaaa........
            .....aaaaaaaaaaaa........
            ......aaaaaaaaaa.........
            .....aa.cc..ccaa.........
            .....aa.cc.cccaa.........
            .....aa.cc.cc.aa.........
            .........................
            `,img`
            .........................
            ..............aaaaaa.....
            .............aaaaaaa.....
            .............aafffff.....
            .............afaadff.....
            .............aaaadddd....
            .............aaaadddd....
            ......aaaaaaaaaaaaaa.....
            .....aaaaaaaaaaaaa.......
            ...aaaaaaaaaaaaaaa.......
            ...aaaaaaaaaaaaaaa.......
            ...aaaaaaaaaaaaaaa.......
            .....aaaaaaaaaaaaa.......
            .....aaaaaaaaaaaa........
            .....aaaaaaaaaaaa........
            ......aaaaaaaaaa.........
            .....ccaaa..ccaa.........
            ....ccc.aaacccaa.........
            ....cc...aacc.aa.........
            .........................
            `,img`
            .........................
            ..............aaaaaa.....
            .............aaaaaaa.....
            .............aafffff.....
            .............afaadff.....
            .............aaaadddd....
            .............aaaadddd....
            ......aaaaaaaaaaaaaa.....
            .....aaaaaaaaaaaaa.......
            ...aaaaaaaaaaaaaaa.......
            ...aaaaaaaaaaaaaaa.......
            ...aaaaaaaaaaaaaaa.......
            .....aaaaaaaaaaaaa.......
            .....aaaaaaaaaaaa........
            .....aaaaaaaaaaaa........
            ......aaaaaaaaaa.........
            .....aa.aa..ccaa.........
            .....aa.aa.cccaa.........
            .....aa.aa.cc.aa.........
            .........................
            `,img`
            .........................
            ..............aaaaaa.....
            .............aaaaaaa.....
            .............aafffff.....
            .............afaadff.....
            .............aaaadddd....
            .............aaaadddd....
            ......aaaaaaaaaaaaaa.....
            .....aaaaaaaaaaaaa.......
            ...aaaaaaaaaaaaaaa.......
            ...aaaaaaaaaaaaaaa.......
            ...aaaaaaaaaaaaaaa.......
            .....aaaaaaaaaaaaa.......
            .....aaaaaaaaaaaac.......
            .....aaaaaaaaaaaacc......
            ......caaaaaaaaacccc.....
            .....cccaa....aa.ccc.....
            .....cc.aa....aa..cc.....
            .....cc.aa....aa..cc.....
            .........................
            `,img`
            .........................
            ..............aaaaaa.....
            .............aaaaaaa.....
            .............aafffff.....
            .............afaadff.....
            .............aaaadddd....
            .............aaaadddd....
            ......aaaaaaaaaaaaaa.....
            .....aaaaaaaaaaaaa.......
            ...aaaaaaaaaaaaaaa.......
            ...aaaaaaaaaaaaaaa.......
            ...aaaaaaaaaaaaaaa.......
            .....aaaaaaaaaaaaa.......
            .....aaaaaaaaaaaa........
            .....aaaaaaaaaaaa........
            ......aaaaaaaaaa.........
            .......aa.cc..aa.........
            .......aa.cc..aa.........
            .......aa.cc..aa.........
            .........................
            `],
        200,
        true
        )
        no_no = true
        for (let value of sprites.allOfKind(SpriteKind.yes)) {
            value.setVelocity(-50, 0)
        }
    }
})
sprites.onOverlap(SpriteKind.p1, SpriteKind.flag, function (sprite, otherSprite) {
    game.over(true)
})
controller.anyButton.onEvent(ControllerButtonEvent.Released, function () {
    if (Traffic_Light && !(controller.anyButton.isPressed())) {
        animation.stopAnimation(animation.AnimationTypes.All, racer_1)
        no_no = false
        for (let value of sprites.allOfKind(SpriteKind.yes)) {
            value.setVelocity(0, 0)
        }
    }
})
sprites.onOverlap(SpriteKind.p2, SpriteKind.flag, function (sprite, otherSprite) {
    game.over(false)
})
function an (racer: Sprite) {
    projectile2 = sprites.createProjectileFromSide(img`
        . . . 6 6 6 7 6 6 6 6 . . . . . . . 
        . . 7 6 6 6 7 6 6 6 7 6 . . . . . . 
        . . 6 7 6 6 7 6 6 7 6 6 6 6 . . . . 
        . 6 6 6 7 7 6 7 7 6 6 6 6 6 . . . . 
        c 6 6 7 7 6 6 7 6 7 6 6 6 6 6 7 f 7 
        c c c 6 6 6 6 7 6 6 7 7 6 6 6 7 7 7 
        . 7 c c 6 6 6 7 6 6 6 6 b b b b b b 
        7 7 . c c c c 6 6 c c c . . . . . . 
        7 . . . 7 7 c c c c 7 7 . . . . . . 
        7 . . 7 7 . . . . . 7 7 . . . . . . 
        . . . 7 . . . . . . . 7 7 . . . . . 
        `, -100, 0)
    projectile2.setKind(SpriteKind.ob)
    projectile2.bottom = racer.bottom
    projectile2.lifespan = 1000
}
function doSomething () {
    if (Traffic_Light) {
        animation.runImageAnimation(
        racer_2,
        [img`
            ..........555.f.f555
            ...........53555535.
            ...........fffffff..
            ..........f.55fff55.
            ............5555555.
            ............555555f.
            ...........55e5..ff.
            ...........5555.....
            ...........5e55.....
            ...........5555.....
            ...........5555.....
            ...........55e5.....
            ..........55555.....
            .........555555.....
            .....5555e5555......
            ....555eee55555.....
            ...55555555555......
            ...5ee5555ee55......
            ...55ee555e554......
            ...55555555.44......
            ...55.44.55.44......
            ...55.44.55.44......
            ...55.44.55.44......
            ...55.44.55.44......
            ...55.44.55.........
            `,img`
            ..........555.f.f555
            ...........53555535.
            ...........fffffff..
            ..........f.55fff55.
            ............5555555.
            ............555555f.
            ...........55e5..ff.
            ...........5555.....
            ...........5e55.....
            ...........5555.....
            ...........5555.....
            ...........55e5.....
            ..........55555.....
            .........555555.....
            .....5555e5555......
            ....555eee55555.....
            ...55555555555......
            ...5ee5555ee55......
            ...55ee555e554......
            ..555555555544......
            .555..44..5554......
            .55...44...555......
            .55...44....555.....
            .55...44....4555....
            .55...44......55....
            `,img`
            ..........555.f.f555
            ...........53555535.
            ...........fffffff..
            ..........f.55fff55.
            ............5555555.
            ............555555f.
            ...........55e5..ff.
            ...........5555.....
            ...........5e55.....
            ...........5555.....
            ...........5555.....
            ...........55e5.....
            ..........55555.....
            .........555555.....
            .....5555e5555......
            ....555eee55555.....
            ...55555555555......
            ...5ee5555ee55......
            ...55ee555e554......
            ....5555555544......
            ....5544..555.......
            ...45544..4555......
            ..4455...44.555.....
            .44455...44..555....
            .44.55...44...55....
            `],
        200,
        true
        )
        yes_yes = true
        for (let value of sprites.allOfKind(SpriteKind.no)) {
            value.setVelocity(turtle, 0)
        }
    }
}
sprites.onDestroyed(SpriteKind.ob, function (sprite) {
    projectile3 = sprites.createProjectileFromSprite(img`
        . . . 6 6 6 7 6 6 6 6 . . . . . . . 
        . . 7 6 6 6 7 6 6 6 7 6 . . . . . . 
        . . 6 7 6 6 7 6 6 7 6 6 6 6 . . . . 
        . 6 6 6 7 7 6 7 7 6 6 6 6 6 . . . . 
        c 6 6 7 7 6 6 7 6 7 6 6 6 6 6 7 f 7 
        c c c 6 6 6 6 7 6 6 7 7 6 6 6 7 7 7 
        . 7 c c 6 6 6 7 6 6 6 6 b b b b b b 
        7 7 . c c c c 6 6 c c c . . . . . . 
        7 . . . 7 7 c c c c 7 7 . . . . . . 
        7 . . 7 7 . . . . . 7 7 . . . . . . 
        . . . 7 . . . . . . . 7 7 . . . . . 
        `, sprite, 0, 0)
    projectile3.ay = -40
    projectile3.setFlag(SpriteFlag.GhostThroughWalls, true)
    for (let index = 0; index < 4; index++) {
        projectile3.startEffect(effects.fire)
    }
})
function doSomething2 () {
    if (Traffic_Light) {
        animation.stopAnimation(animation.AnimationTypes.ImageAnimation, racer_2)
        yes_yes = false
        for (let value of sprites.allOfKind(SpriteKind.yes)) {
            value.setVelocity(0, 0)
        }
    }
}
let new_scene: Sprite = null
let projectile: Sprite = null
let projectile3: Sprite = null
let yes_yes = false
let projectile2: Sprite = null
let no_no = false
let race_started = false
let textSprite: TextSprite = null
let racer_2: Sprite = null
let racer_1: Sprite = null
let turtle = 0
let Traffic_Light: Sprite = null
Traffic_Light = sprites.create(img`
    ...............ffffffffffffffffffffffffffff.................
    ...............ffffffffffffffffffffffffffff.................
    ...............ffffffffffffffffffffffffffff.................
    ...............ffffffffffffffffffffffffffff.................
    ...............ffffffffffffffffffffffffffff.................
    ...............ffffffffffbbbbbbbbbfffffffff.................
    ...............ffffffffbbbbbbbbbbbbbfffffff.................
    ...............fffffffbbbbbbbbbbbbbbbffffff.................
    ...............ffffffbbbbbbbbbbbbbbbbbfffff.................
    ...............fffffbbbbbbbbbbbbbbbbbbbffff.................
    ...............fffffbbbbbbbbbbbbbbbbbbbffff.................
    ...............ffffbbbbbbbbbbbbbbbbbbbbbfff.................
    ...............ffffbbbbbbbbbbbbbbbbbbbbbfff.................
    ...............ffffbbbbbbbbbbbbbbbbbbbbbfff.................
    ...............ffffbbbbbbbbbbbbbbbbbbbbbfff.................
    ...............ffffbbbbbbbbbbbbbbbbbbbbbfff.................
    ...............ffffbbbbbbbbbbbbbbbbbbbbbfff.................
    ...............ffffbbbbbbbbbbbbbbbbbbbbbfff.................
    ...............ffffbbbbbbbbbbbbbbbbbbbbbfff.................
    ...............ffffbbbbbbbbbbbbbbbbbbbbbfff.................
    ...............fffffbbbbbbbbbbbbbbbbbbbffff.................
    ...............fffffbbbbbbbbbbbbbbbbbbbffff.................
    ...............ffffffbbbbbbbbbbbbbbbbbfffff.................
    ...............fffffffbbbbbbbbbbbbbbbffffff.................
    ...............ffffffffbbbbbbbbbbbbbfffffff.................
    ...............ffffffffffbbbbbbbbbfffffffff.................
    ...............ffffffffffffffffffffffffffff.................
    ...............ffffffffffffffffffffffffffff.................
    ...............ffffffffffffffffffffffffffff.................
    ...............ffffffffffffffffffffffffffff.................
    ...............ffffffffffeeeeeeeeefffffffff.................
    ...............ffffffffeeeeeeeeeeeeefffffff.................
    ...............fffffffeeeeeeeeeeeeeeeffffff.................
    ...............ffffffeeeeeeeeeeeeeeeeefffff.................
    ...............fffffeeeeeeeeeeeeeeeeeeeffff.................
    ...............fffffeeeeeeeeeeeeeeeeeeeffff.................
    ...............ffffeeeeeeeeeeeeeeeeeeeeefff.................
    ...............ffffeeeeeeeeeeeeeeeeeeeeefff.................
    ...............ffffeeeeeeeeeeeeeeeeeeeeefff.................
    ...............ffffeeeeeeeeeeeeeeeeeeeeefff.................
    ...............ffffeeeeeeeeeeeeeeeeeeeeefff.................
    ...............ffffeeeeeeeeeeeeeeeeeeeeefff.................
    ...............ffffeeeeeeeeeeeeeeeeeeeeefff.................
    ...............ffffeeeeeeeeeeeeeeeeeeeeefff.................
    ...............ffffeeeeeeeeeeeeeeeeeeeeefff.................
    ...............fffffeeeeeeeeeeeeeeeeeeeffff.................
    ...............fffffeeeeeeeeeeeeeeeeeeeffff.................
    ...............ffffffeeeeeeeeeeeeeeeeefffff.................
    ...............fffffffeeeeeeeeeeeeeeeffffff.................
    ...............ffffffffeeeeeeeeeeeeefffffff.................
    ...............ffffffffffeeeeeeeeefffffffff.................
    ...............ffffffffffffffffffffffffffff.................
    ...............ffffffffffffffffffffffffffff.................
    ...............ffffffffffffffffffffffffffff.................
    ...............ffffffffffffffffffffffffffff.................
    ...............ffffffffffffffffffffffffffff.................
    ...............ffffffffffffffffffffffffffff.................
    ...............ffffffffff666666666fffffffff.................
    ...............ffffffff6666666666666fffffff.................
    ...............fffffff666666666666666ffffff.................
    ...............ffffff66666666666666666fffff.................
    ...............fffff6666666666666666666ffff.................
    ...............fffff6666666666666666666ffff.................
    ...............ffff666666666666666666666fff.................
    ...............ffff666666666666666666666fff.................
    ...............ffff666666666666666666666fff.................
    ...............ffff666666666666666666666fff.................
    ...............ffff666666666666666666666fff.................
    ...............ffff666666666666666666666fff.................
    ...............ffff666666666666666666666fff.................
    ...............ffff666666666666666666666fff.................
    ...............ffff666666666666666666666fff.................
    ...............fffff6666666666666666666ffff.................
    ...............fffff6666666666666666666ffff.................
    ...............ffffff66666666666666666fffff.................
    ...............fffffff666666666666666ffffff.................
    ...............ffffffff6666666666666fffffff.................
    ...............ffffffffff666666666fffffffff.................
    ...............ffffffffffffffffffffffffffff.................
    ...............ffffffffffffffffffffffffffff.................
    `, SpriteKind.Player)
Traffic_Light.z = 9766235693853
scene.setBackgroundColor(9)
tiles.setTilemap(tilemap`level2`)
turtle = -100
let line = sprites.create(img`
    ccccccccccccccccccccccccccccccccccc5cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc5ccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccc11111ccccc11111ccccc1111ccccccc5cccccc1111cccc11111ccccc11111ccccc1111cccccc111ccccc11111ccccc1111cccccc5cccc11111ccccc11111ccccc1111ccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccc5cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc5ccccccccccccccccccccccccccccccccccccccccccccccccccc
    `, SpriteKind.Player)
racer_1 = sprites.create(img`
    ...........aaaaaa.
    ..........aaaaaaa.
    ..........aafffff.
    ..........afaadff.
    ..........aaaadddd
    ..........aaaadddd
    ...aaaaaaaaaaaaaa.
    ..aaaaaaaaaaaaa...
    aaaaaaaaaaaaaaa...
    aaaaaaaaaaaaaaa...
    aaaaaaaaaaaaaaa...
    ..aaaaaaaaaaaaa...
    ..aaaaaaaaaaaa....
    ..aaaaaaaaaaaa....
    ...aaaaaaaaaa.....
    ....aa.cc..aa.....
    ....aa.cc..aa.....
    ....aa.cc..aa.....
    `, SpriteKind.Player)
racer_1.bottom = 55
racer_2 = sprites.create(img`
    ..........555.f.f555
    ...........53555535.
    ...........fffffff..
    ..........f.55fff55.
    ............5555555.
    ............555555f.
    ...........55e5..ff.
    ...........5555.....
    ...........5e55.....
    ...........5555.....
    ...........5555.....
    ...........55e5.....
    ..........55555.....
    .........555555.....
    .....5555e5555......
    ....555eee55555.....
    ...55555555555......
    ...5ee5555ee55......
    ...55ee555e554......
    ...55555555.44......
    ...55.44.55.44......
    ...55.44.55.44......
    ...55.44.55.44......
    ...55.44.55.44......
    ...55.44.55.........
    `, SpriteKind.Player)
racer_2.bottom = 120
let p1 = sprites.create(img`
    . 4 4 4 4 4 . 
    4 1 1 4 4 1 4 
    4 1 4 1 4 1 4 
    4 1 1 4 4 1 4 
    4 1 4 4 4 1 4 
    . 4 4 4 4 4 . 
    . . 4 4 4 . . 
    . . . 4 . . . 
    `, SpriteKind.p1)
p1.y += -5
p1.x = 5
let p2 = sprites.create(img`
    . . . 2 . . . 
    . . 2 2 2 . . 
    . 2 2 2 2 2 . 
    2 1 1 2 1 1 2 
    2 1 2 1 2 1 2 
    2 1 1 2 1 2 2 
    2 1 2 2 1 1 2 
    . 2 2 2 2 2 . 
    `, SpriteKind.p2)
p2.y += 5
p2.x = 5
let fl = sprites.create(img`
    f f 1 1 f f 1 1 
    f f 1 1 f f 1 1 
    1 1 f f 1 1 f f 
    1 1 f f 1 1 f f 
    f f 1 1 f f 1 1 
    f f 1 1 f f 1 1 
    1 1 f f 1 1 f f 
    1 1 f f 1 1 f f 
    `, SpriteKind.flag)
fl.right = 159
timer.background(function () {
    pause(1000)
    Traffic_Light.image.replace(11, 2)
    pause(1000)
    Traffic_Light.image.replace(2, 11)
    pause(100)
    Traffic_Light.image.replace(14, 5)
    pause(1000)
    Traffic_Light.image.replace(5, 14)
    pause(100)
    Traffic_Light.image.replace(6, 7)
    pause(1000)
    Traffic_Light.destroy()
    textSprite = textsprite.create("GO!")
    textSprite.setOutline(1, 6)
    textSprite.setMaxFontHeight(64)
    textSprite.setPosition(80, 60)
    pause(1000)
    textSprite.destroy()
    race_started = true
    doSomething()
})
game.onUpdateInterval(2000, function () {
    if (no_no && Math.percentChance(50)) {
        if (true) {
            an(racer_1)
        } else {
            projectile = sprites.createProjectileFromSide(img`
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . 2 . . . . . . . 
                . . . . 7 7 . . 2 2 . . . . . . 
                . . . . . 7 7 . 2 2 2 . . 4 . . 
                a a . . . . 7 7 7 . . . . . 4 . 
                a 7 7 . . . . 7 7 7 . . . . 7 . 
                . . 7 . . . . 7 . 7 7 . . 7 . . 
                . . 7 . . . . 7 . . . . . 7 . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                `, -50, 0)
            projectile.setKind(SpriteKind.yes)
            projectile.bottom = racer_1.bottom
        }
    }
})
game.onUpdateInterval(2000, function () {
    if (yes_yes) {
        new_scene = sprites.createProjectileFromSide(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . 2 . . . . . . . 
            . . . . 7 7 . . 2 2 . . . . . . 
            . . . . . 7 7 . 2 2 2 . . 4 . . 
            a a . . . . 7 7 7 . . . . . 4 . 
            a 7 7 . . . . 7 7 7 . . . . 7 . 
            . . 7 . . . . 7 . 7 7 . . 7 . . 
            . . 7 . . . . 7 . . . . . 7 . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, turtle, 0)
        new_scene.setKind(SpriteKind.no)
        new_scene.bottom = racer_2.bottom
    }
})
game.onUpdateInterval(100, function () {
    if (no_no) {
        p1.x += 1
    }
    if (yes_yes) {
        p2.x += 1
    }
})
